### ISSUE TITLE
Forgot to update plugin version?

### ISSUE THREAD

**Issue by manolitto** [vookimedlo/OctoPrint-Prusa-Mini-ETA#1]
https://github.com/vookimedlo/OctoPrint-Prusa-Mini-ETA/blob/7b9bb9568805f920f7d2e76760b79d7f2dba8fe6/setup.py#L33

**Comment by vookimedlo** [comment]
You are correct. Thanks!

**Comment by vookimedlo** [comment]
Updated and tagged the new release => 0.1.2
