### ISSUE TITLE
The plugin says incompatible in octoprint 1.4.2

### ISSUE THREAD

**Issue by Danbuhr** [vookimedlo/OctoPrint-Prusa-Mini-ETA#3]
Really wanna try out the plugin. Is it easy to bump the compatible version? :)

Kind regards

Dan

**Comment by vookimedlo** [comment]
Hi Dan,

This plugin is compatible with 1.4.0+ Octoprint. But it supports python3 only, not the deprecated python2.

Are you sure that your Octoprint instance is hosted by the python3?

Thanks,

Michal
